packages:
- ./
extra-deps:
- ivory-0.1.0.3
- ivory-artifact-0.1.0.3
- ivory-backend-c-0.1.0.3
- ivory-opts-0.1.0.3
- language-c-quote-0.11.6
- mainland-pretty-0.4.1.4
- exception-mtl-0.4
- symbol-0.2.4
resolver: lts-5.3
